/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialFundraisingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CACHE_TIMEOUT"
      | "callbackDecryptAvailableBalance"
      | "callbackDecryptMyContribution"
      | "callbackDecryptTotalRaised"
      | "campaignContract"
      | "campaignCount"
      | "campaigns"
      | "cancelCampaign"
      | "claimTokens"
      | "confidentialProtocolId"
      | "contribute"
      | "createCampaign"
      | "finalizeCampaign"
      | "getCampaign"
      | "getCampaignContributors"
      | "getContributionStatus"
      | "getEncryptedContribution"
      | "getEncryptedTotalRaised"
      | "getMyContribution"
      | "getTotalRaised"
      | "getTotalRaisedStatus"
      | "hasClaimed"
      | "hasClaimedTokens"
      | "hasContribution"
      | "requestMyContributionDecryption"
      | "requestTotalRaisedDecryption"
      | "shareVault"
      | "submitMyContributionDecryption"
      | "submitTotalRaisedDecryption"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCancelled"
      | "CampaignCreated"
      | "CampaignFailed"
      | "CampaignFinalized"
      | "ContributionMade"
      | "PublicDecryptionVerified"
      | "TokensClaimed"
      | "TokensDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CACHE_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "callbackDecryptAvailableBalance",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackDecryptMyContribution",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackDecryptTotalRaised",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeCampaign",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignContributors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributionStatus",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedContribution",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotalRaised",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyContribution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRaised",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRaisedStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimedTokens",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasContribution",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestMyContributionDecryption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestTotalRaisedDecryption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shareVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitMyContributionDecryption",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTotalRaisedDecryption",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CACHE_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackDecryptAvailableBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackDecryptMyContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackDecryptTotalRaised",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignContributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotalRaised",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRaised",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRaisedStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestMyContributionDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTotalRaisedDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shareVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitMyContributionDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTotalRaisedDecryption",
    data: BytesLike
  ): Result;
}

export namespace CampaignCancelledEvent {
  export type InputTuple = [campaignId: BigNumberish];
  export type OutputTuple = [campaignId: bigint];
  export interface OutputObject {
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    owner: AddressLike,
    title: string,
    targetAmount: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    owner: string,
    title: string,
    targetAmount: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    owner: string;
    title: string;
    targetAmount: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignFailedEvent {
  export type InputTuple = [campaignId: BigNumberish];
  export type OutputTuple = [campaignId: bigint];
  export interface OutputObject {
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignFinalizedEvent {
  export type InputTuple = [campaignId: BigNumberish, targetReached: boolean];
  export type OutputTuple = [campaignId: bigint, targetReached: boolean];
  export interface OutputObject {
    campaignId: bigint;
    targetReached: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionMadeEvent {
  export type InputTuple = [campaignId: BigNumberish, contributor: AddressLike];
  export type OutputTuple = [campaignId: bigint, contributor: string];
  export interface OutputObject {
    campaignId: bigint;
    contributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicDecryptionVerifiedEvent {
  export type InputTuple = [
    handlesList: BytesLike[],
    abiEncodedCleartexts: BytesLike
  ];
  export type OutputTuple = [
    handlesList: string[],
    abiEncodedCleartexts: string
  ];
  export interface OutputObject {
    handlesList: string[];
    abiEncodedCleartexts: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensClaimedEvent {
  export type InputTuple = [campaignId: BigNumberish, contributor: AddressLike];
  export type OutputTuple = [campaignId: bigint, contributor: string];
  export interface OutputObject {
    campaignId: bigint;
    contributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensDistributedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    contributor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    contributor: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialFundraising extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialFundraising;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialFundraisingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CACHE_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  callbackDecryptAvailableBalance: TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  callbackDecryptMyContribution: TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  callbackDecryptTotalRaised: TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  campaignContract: TypedContractMethod<[], [string], "view">;

  campaignCount: TypedContractMethod<[], [bigint], "view">;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        owner: string;
        title: string;
        description: string;
        totalRaised: string;
        targetAmount: bigint;
        deadline: bigint;
        finalized: boolean;
        cancelled: boolean;
        tokenAddress: string;
      }
    ],
    "view"
  >;

  cancelCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimTokens: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  contribute: TypedContractMethod<
    [
      campaignId: BigNumberish,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  createCampaign: TypedContractMethod<
    [
      title: string,
      description: string,
      target: BigNumberish,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  finalizeCampaign: TypedContractMethod<
    [campaignId: BigNumberish, tokenName: string, tokenSymbol: string],
    [void],
    "nonpayable"
  >;

  getCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean, boolean, string] & {
        owner: string;
        title: string;
        description: string;
        targetAmount: bigint;
        deadline: bigint;
        finalized: boolean;
        cancelled: boolean;
        tokenAddress: string;
      }
    ],
    "view"
  >;

  getCampaignContributors: TypedContractMethod<
    [campaignId: BigNumberish],
    [string[]],
    "view"
  >;

  getContributionStatus: TypedContractMethod<
    [campaignId: BigNumberish, user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        status: bigint;
        contribution: bigint;
        cacheExpiry: bigint;
      }
    ],
    "view"
  >;

  getEncryptedContribution: TypedContractMethod<
    [campaignId: BigNumberish, user: AddressLike],
    [string],
    "view"
  >;

  getEncryptedTotalRaised: TypedContractMethod<
    [campaignId: BigNumberish],
    [string],
    "view"
  >;

  getMyContribution: TypedContractMethod<
    [campaignId: BigNumberish],
    [bigint],
    "view"
  >;

  getTotalRaised: TypedContractMethod<
    [campaignId: BigNumberish],
    [bigint],
    "view"
  >;

  getTotalRaisedStatus: TypedContractMethod<
    [campaignId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        status: bigint;
        totalRaised: bigint;
        cacheExpiry: bigint;
      }
    ],
    "view"
  >;

  hasClaimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasClaimedTokens: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasContribution: TypedContractMethod<
    [campaignId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  requestMyContributionDecryption: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestTotalRaisedDecryption: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  shareVault: TypedContractMethod<[], [string], "view">;

  submitMyContributionDecryption: TypedContractMethod<
    [campaignId: BigNumberish, cleartextAmount: BigNumberish, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  submitTotalRaisedDecryption: TypedContractMethod<
    [campaignId: BigNumberish, cleartextTotal: BigNumberish, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CACHE_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "callbackDecryptAvailableBalance"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackDecryptMyContribution"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackDecryptTotalRaised"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "campaignContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "campaignCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        owner: string;
        title: string;
        description: string;
        totalRaised: string;
        targetAmount: bigint;
        deadline: bigint;
        finalized: boolean;
        cancelled: boolean;
        tokenAddress: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelCampaign"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTokens"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<
    [
      campaignId: BigNumberish,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      target: BigNumberish,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeCampaign"
  ): TypedContractMethod<
    [campaignId: BigNumberish, tokenName: string, tokenSymbol: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean, boolean, string] & {
        owner: string;
        title: string;
        description: string;
        targetAmount: bigint;
        deadline: bigint;
        finalized: boolean;
        cancelled: boolean;
        tokenAddress: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCampaignContributors"
  ): TypedContractMethod<[campaignId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getContributionStatus"
  ): TypedContractMethod<
    [campaignId: BigNumberish, user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        status: bigint;
        contribution: bigint;
        cacheExpiry: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedContribution"
  ): TypedContractMethod<
    [campaignId: BigNumberish, user: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedTotalRaised"
  ): TypedContractMethod<[campaignId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getMyContribution"
  ): TypedContractMethod<[campaignId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalRaised"
  ): TypedContractMethod<[campaignId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalRaisedStatus"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        status: bigint;
        totalRaised: bigint;
        cacheExpiry: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimedTokens"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasContribution"
  ): TypedContractMethod<
    [campaignId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestMyContributionDecryption"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestTotalRaisedDecryption"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "shareVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitMyContributionDecryption"
  ): TypedContractMethod<
    [campaignId: BigNumberish, cleartextAmount: BigNumberish, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitTotalRaisedDecryption"
  ): TypedContractMethod<
    [campaignId: BigNumberish, cleartextTotal: BigNumberish, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CampaignCancelled"
  ): TypedContractEvent<
    CampaignCancelledEvent.InputTuple,
    CampaignCancelledEvent.OutputTuple,
    CampaignCancelledEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignFailed"
  ): TypedContractEvent<
    CampaignFailedEvent.InputTuple,
    CampaignFailedEvent.OutputTuple,
    CampaignFailedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignFinalized"
  ): TypedContractEvent<
    CampaignFinalizedEvent.InputTuple,
    CampaignFinalizedEvent.OutputTuple,
    CampaignFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionMade"
  ): TypedContractEvent<
    ContributionMadeEvent.InputTuple,
    ContributionMadeEvent.OutputTuple,
    ContributionMadeEvent.OutputObject
  >;
  getEvent(
    key: "PublicDecryptionVerified"
  ): TypedContractEvent<
    PublicDecryptionVerifiedEvent.InputTuple,
    PublicDecryptionVerifiedEvent.OutputTuple,
    PublicDecryptionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "TokensClaimed"
  ): TypedContractEvent<
    TokensClaimedEvent.InputTuple,
    TokensClaimedEvent.OutputTuple,
    TokensClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TokensDistributed"
  ): TypedContractEvent<
    TokensDistributedEvent.InputTuple,
    TokensDistributedEvent.OutputTuple,
    TokensDistributedEvent.OutputObject
  >;

  filters: {
    "CampaignCancelled(uint256)": TypedContractEvent<
      CampaignCancelledEvent.InputTuple,
      CampaignCancelledEvent.OutputTuple,
      CampaignCancelledEvent.OutputObject
    >;
    CampaignCancelled: TypedContractEvent<
      CampaignCancelledEvent.InputTuple,
      CampaignCancelledEvent.OutputTuple,
      CampaignCancelledEvent.OutputObject
    >;

    "CampaignCreated(uint256,address,string,uint256,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignFailed(uint16)": TypedContractEvent<
      CampaignFailedEvent.InputTuple,
      CampaignFailedEvent.OutputTuple,
      CampaignFailedEvent.OutputObject
    >;
    CampaignFailed: TypedContractEvent<
      CampaignFailedEvent.InputTuple,
      CampaignFailedEvent.OutputTuple,
      CampaignFailedEvent.OutputObject
    >;

    "CampaignFinalized(uint256,bool)": TypedContractEvent<
      CampaignFinalizedEvent.InputTuple,
      CampaignFinalizedEvent.OutputTuple,
      CampaignFinalizedEvent.OutputObject
    >;
    CampaignFinalized: TypedContractEvent<
      CampaignFinalizedEvent.InputTuple,
      CampaignFinalizedEvent.OutputTuple,
      CampaignFinalizedEvent.OutputObject
    >;

    "ContributionMade(uint256,address)": TypedContractEvent<
      ContributionMadeEvent.InputTuple,
      ContributionMadeEvent.OutputTuple,
      ContributionMadeEvent.OutputObject
    >;
    ContributionMade: TypedContractEvent<
      ContributionMadeEvent.InputTuple,
      ContributionMadeEvent.OutputTuple,
      ContributionMadeEvent.OutputObject
    >;

    "PublicDecryptionVerified(bytes32[],bytes)": TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
    PublicDecryptionVerified: TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;

    "TokensClaimed(uint256,address)": TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;
    TokensClaimed: TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;

    "TokensDistributed(uint16,address,uint256)": TypedContractEvent<
      TokensDistributedEvent.InputTuple,
      TokensDistributedEvent.OutputTuple,
      TokensDistributedEvent.OutputObject
    >;
    TokensDistributed: TypedContractEvent<
      TokensDistributedEvent.InputTuple,
      TokensDistributedEvent.OutputTuple,
      TokensDistributedEvent.OutputObject
    >;
  };
}
